[CI] Fix ref_llvm and ref_translator in on-push-verification-in-tree task

diff --git a/.github/workflows/on-push-verification-in-tree.yml b/.github/workflows/on-push-verification-in-tree.yml
--- a/.github/workflows/on-push-verification-in-tree.yml
+++ b/.github/workflows/on-push-verification-in-tree.yml
@@ -35,9 +35,23 @@ jobs:
       - name: Checkout opencl-clang sources for action files
         uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
 
+      # This step will fail when the branch naming scheme 'ocl-open-XXX' changes!
+      - name: Parse LLVM version from branch name
+        id: check-llvm-version
+        run: |
+          BRANCH="${{ github.base_ref }}"          # on: pull_request, otherwise null
+          BRANCH=${BRANCH:-${{ github.ref_name }}} # on: push
+          LLVM_VERSION_LONG=$(echo $BRANCH | grep -oP 'ocl-open-\K\d+') # Eg. 190 for LLVM 19
+          if [ -z "$LLVM_VERSION_LONG" ]; then
+            echo "[OPENCL-CLANG] Error: Could not parse LLVM version from branch name '$BRANCH'"
+            exit 1
+          fi
+          LLVM_VERSION_SHORT=${LLVM_VERSION_LONG::-1}        # Eg. 19  for LLVM 19
+          echo "llvm_version=$LLVM_VERSION_SHORT" >> $GITHUB_OUTPUT
+
       - name: Run build-opencl-clang action
         uses: ./.github/actions/build-opencl-clang
         with:
-          ref_llvm: main
-          ref_translator: main
+          ref_llvm: release/${{ steps.check-llvm-version.outputs.llvm_version }}.x
+          ref_translator: llvm_release_${{ steps.check-llvm-version.outputs.llvm_version }}0
           ref_opencl-clang: ${{ github.ref }}
